Repository ZapeeoSheikh/Hacktoberfest-22, pull requests merged in 2022-10, with the labels that each got.

#36 Added MultilevelInheritance.java
  Java/Inheritance/HeirarchialInheritance.java
  Java/Inheritance/MultilevelInheritance.java
  Java/Inheritance/SingleInheritance.java
Labels: good first issue

#37 Create reverseLinkedList.java
  Java/LinkedList/mergeTwoSortedLists.java
  Java/LinkedList/reverseLinkedList.java
Labels: help wanted

#39 Create HomePageNetflix.dart
  Dart/HomePageNetflix.dart
Labels: hacktoberfest-accepted

#38 Create LRUcache.java
  Java/LinkedList/LRUcache.java
  Java/LinkedList/reverseNodesInKGroups.java
Labels: good first issue, hacktoberfest-accepted

#40 Create DiamTree.cpp
  C++/DiamTree.cpp
Labels: hacktoberfest-accepted

#41 Create BottomNavigationBar.dart
  Dart/BottomNavigationBar.dart
Labels: hacktoberfest-accepted

#42 Update hello.sql
  SQL/hello.sql
Labels: enhancement, hacktoberfest-accepted

#52 adding simple features
  python/2- Guess the Number.py
  python/celsius_to_fahrenheit.py
  python/quizgame.py
Labels: enhancement, hacktoberfest-accepted

#51 added 2 backtracking programs in java
  Java/Knight.java
  Java/RatMaze.java
Labels: help wanted, hacktoberfest-accepted

#48 Create shinchan.py
  python/shinchan.py
Labels: good first issue, hacktoberfest-accepted

#46 Added implementation of insertion sort in js
  Javascript/insertion_sort.js
Labels: duplicate

#45 Adding bash files
  Bash/argument.sh
  Bash/basics.sh
  Bash/loops.sh
Labels: invalid

#43 goodnight-greetings
  Javascript/good-night/favicon.ico
  Javascript/good-night/index.html
  Javascript/good-night/songs.mp3
Labels: hacktoberfest-accepted

#70 Created creditCard_Validator.cpp Fixes #47
  C++/creditcard_validator.cpp
Labels: good first issue, hacktoberfest-accepted

#68 send email python script
  python/send_email.py
Labels: help wanted, hacktoberfest-accepted

#67 Create joke_api_calling.dart
  Dart/joke_api_calling.dart
Labels: enhancement, hacktoberfest-accepted

#66 Fractional Knapsack Problem
  fractional_knapsack.py
Labels: hacktoberfest-accepted

#64 Create armstrong number or not
  python/armstrong number or not
Labels: bug, invalid

#57 Added Snake Game
  python/snake.py
Labels: good first issue, hacktoberfest-accepted

#56 Hello World in Perl
  Perl
Labels: invalid

#54 Add pymid, python script to generate pyramid.
  python/pymid-python pyramid
Labels: good first issue, hacktoberfest-accepted

#58 Rabin Karp Algorithm for pattern searching
  RabinKarp.java
Labels: enhancement, hacktoberfest-accepted

#60 Created spiral_matrix.py
  python/spiral_matrix.py
Labels: question, hacktoberfest-accepted

#61 Create LCM of two numbers
  C++/LCM of two numbers
Labels: duplicate

#62 Create Prime Number
  C#/Prime Number
Labels: good first issue, hacktoberfest-accepted

#65 Bubble Sort in Java
  Java/Sort.java
Labels: help wanted, hacktoberfest-accepted
